### ISSUE TITLE
Slackに投稿されるissue一覧のフォーマットを変更する

### ISSUE THREAD

**Issue by HomMarkHunt** [javamas/chappie#4]
## 前提

cron jobでMilestone毎のIssue一覧を (最新順??Noが大きい順??) で投稿してくれているが、
自分がAssingneeのIssueをまとめて見たい。
## 要望

希望のフォーマットはこちら。
### 現在

> みなさん！今進行中のMilestoneのIssueを報告するね:triangular_flag_on_post:
> Milestone: some milestone
> ## Priority
> 
> yyyy/MM/dd(Tue) 〜 yyyy/MM/dd(Wed)
> 
> @User1
> # xxx3 テーブル設計を決める
> 
>  @User1
> # xxx2 何かをを決める
> 
>  @User2
> # xxx1 テーブル設計をなんかする
### 希望

> みなさん！今進行中のMilestoneのIssueを報告するね:triangular_flag_on_post:
> Milestone: some milestone
> ## Priority
> 
> yyyy/MM/dd(Tue) 〜 yyyy/MM/dd(Wed)
> 
> @User1
> 2 issue
> # xxx3 テーブル設計を決める
> # xxx2 何かをを決める
> 
> @User2
> 1 issue
> # xxx1 テーブル設計をなんかする

**Comment by dodoichi** [comment]
ユーザ毎に件数を表示して、個別のissueタイトルとリンクは無くしてもらった方が、スッキリするかな。

ユーザ名がユーザ別にフィルタされたissue一覧へのリンクになってれば、ワンクリックで確認できるね。

**Comment by disc99** [comment]
@HomMarkHunt 
まとめた！

@dodoichi 
ユーザ単位のフィルタは作成しましたが`All xxx issues`、開かないと何がアサインされてるか見えないのと、そもそもスマホとかだとZenhubが入ってないので見れない問題があり、両方出す形にしときました！
各issueがあると見にくいようであればもう少し検討します！

という事後報告です！

**Comment by dodoichi** [comment]
よいですね。ただ、表示順を番号の降順ではなく昇順にしてもらえるといいな。

**Comment by disc99** [comment]
@dodoichi 
対応しました！

**Comment by HomMarkHunt** [comment]
![LGTM](http://lgtm.in/p/kQFnTlaWp)

**Comment by dodoichi** [comment]
![LGTM](http://lgtm.in/p/M8obooj9q)

**Comment by disc99** [comment]
LGTM2つゲットしたのでクローズします！
